import Head from 'next/head';

export default function Home() {
  return (
    <div className='font-bold'>
      <Head>
        <title>Next App Setup</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Next App Setup</h1>
    </div>
  );
}
